In [1]:
import numpy as np

In [2]:
!pip install tensorflow

Collecting tensorflow
  Downloading tensorflow-2.21.0-cp313-cp313-win_amd64.whl.metadata (4.5 kB)
Collecting absl-py>=1.0.0 (from tensorflow)
  Downloading absl_py-2.4.0-py3-none-any.whl.metadata (3.3 kB)
Collecting astunparse>=1.6.0 (from tensorflow)
  Downloading astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=25.9.23 (from tensorflow)
  Downloading flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow)
  Downloading gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
Collecting google_pasta>=0.1.1 (from tensorflow)
  Downloading google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow)
  Downloading libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
Collecting opt_einsum>=2.3.2 (from tensorflow)
  Downloading opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: packaging in c:\users\rkroh\anaconda3\lib\site-packages (from tensorflow) (25.0)
Collecting protobuf<8.0.0,>=6.31.1 (from tensorflow)
  Downloading protobuf-7.34.1-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\rkroh\anaconda3\lib\site-packages (from tensorflow) (2.32.5)
Requirement already satisfied: setuptools in c:\users\rkroh\anaconda3\lib\site-packages (from tensorflow) (80.9.0)
Requirement already satisfied: six>=1.12.0 in c:\users\rkroh\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Collecting termcolor>=1.1.0 (from tensorflow)
  Downloading termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\rkroh\anaconda3\lib\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\rkroh\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow)
  Downloading grpcio-1.80.0-cp313-cp313-win_amd64.whl.metadata (3.9 kB)
Collecting keras>=3.12.0 (from tensorflow)
  Downloading keras-3.14.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\rkroh\anaconda3\lib\site-packages (from tensorflow) (2.3.5)
Collecting h5py<3.15.0,>=3.11.0 (from tensorflow)
  Downloading h5py-3.14.0-cp313-cp313-win_amd64.whl.metadata (2.7 kB)
Collecting ml_dtypes<1.0.0,>=0.5.1 (from tensorflow)
  Downloading ml_dtypes-0.5.4-cp313-cp313-win_amd64.whl.metadata (9.2 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\rkroh\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\rkroh\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\rkroh\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\rkroh\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2025.11.12)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\rkroh\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in c:\users\rkroh\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (14.2.0)
Collecting namex (from keras>=3.12.0->tensorflow)
  Downloading namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
Collecting optree (from keras>=3.12.0->tensorflow)
  Downloading optree-0.19.0-cp313-cp313-win_amd64.whl.metadata (35 kB)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\rkroh\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\rkroh\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\rkroh\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)
Downloading tensorflow-2.21.0-cp313-cp313-win_amd64.whl (351.2 MB)
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 1.3/351.2 MB 4.9 MB/s eta 0:01:12
   ---------------------------------------- 3.1/351.2 MB 5.7 MB/s eta 0:01:02
   ---------------------------------------- 3.9/351.2 MB 4.7 MB/s eta 0:01:15
    --------------------------------------- 5.8/351.2 MB 5.4 MB/s eta 0:01:05
    --------------------------------------- 7.3/351.2 MB 5.5 MB/s eta 0:01:03
   - -------------------------------------- 9.7/351.2 MB 6.3 MB/s eta 0:00:55
   - -------------------------------------- 11.8/351.2 MB 6.0 MB/s eta 0:00:57
   - -------------------------------------- 13.9/351.2 MB 6.3 MB/s eta 0:00:54
   - -------------------------------------- 16.3/351.2 MB 6.2 MB/s eta 0:00:55
   -- ------------------------------------- 18.9/351.2 MB 6.4 MB/s eta 0:00:52
   -- ------------------------------------- 22.0/351.2 MB 7.0 MB/s eta 0:00:47
   -- ------------------------------------- 25.7/351.2 MB 7.6 MB/s eta 0:00:43
   --- ------------------------------------ 28.0/351.2 MB 7.6 MB/s eta 0:00:43
   --- ------------------------------------ 29.4/351.2 MB 7.5 MB/s eta 0:00:44
   --- ------------------------------------ 30.9/351.2 MB 7.4 MB/s eta 0:00:44
   --- ------------------------------------ 34.6/351.2 MB 7.7 MB/s eta 0:00:42
   ---- ----------------------------------- 35.9/351.2 MB 7.2 MB/s eta 0:00:44
   ---- ----------------------------------- 38.0/351.2 MB 7.2 MB/s eta 0:00:44
   ---- ----------------------------------- 41.9/351.2 MB 7.6 MB/s eta 0:00:41
   ----- ---------------------------------- 45.6/351.2 MB 8.0 MB/s eta 0:00:39
   ----- ---------------------------------- 49.5/351.2 MB 8.4 MB/s eta 0:00:37
   ------ --------------------------------- 53.2/351.2 MB 8.6 MB/s eta 0:00:35
   ------ --------------------------------- 56.1/351.2 MB 8.8 MB/s eta 0:00:34
   ------ --------------------------------- 59.5/351.2 MB 9.0 MB/s eta 0:00:33
   ------- -------------------------------- 62.4/351.2 MB 8.9 MB/s eta 0:00:33
   ------- -------------------------------- 68.4/351.2 MB 9.4 MB/s eta 0:00:31
   -------- ------------------------------- 72.4/351.2 MB 9.6 MB/s eta 0:00:29
   -------- ------------------------------- 75.5/351.2 MB 9.8 MB/s eta 0:00:29
   --------- ------------------------------ 79.2/351.2 MB 10.0 MB/s eta 0:00:28
   --------- ------------------------------ 81.3/351.2 MB 9.8 MB/s eta 0:00:28
   --------- ------------------------------ 83.6/351.2 MB 9.8 MB/s eta 0:00:28
   --------- ------------------------------ 87.3/351.2 MB 9.7 MB/s eta 0:00:28
   ---------- ----------------------------- 88.3/351.2 MB 9.5 MB/s eta 0:00:28
   ---------- ----------------------------- 89.9/351.2 MB 9.2 MB/s eta 0:00:29
   ---------- ----------------------------- 92.8/351.2 MB 9.0 MB/s eta 0:00:29
   ---------- ----------------------------- 96.2/351.2 MB 9.1 MB/s eta 0:00:29
   ----------- ---------------------------- 97.5/351.2 MB 8.8 MB/s eta 0:00:29
   ----------- ---------------------------- 98.6/351.2 MB 8.6 MB/s eta 0:00:30
   ----------- ---------------------------- 99.9/351.2 MB 8.5 MB/s eta 0:00:30
   ----------- ---------------------------- 104.3/351.2 MB 8.6 MB/s eta 0:00:29
   ------------ --------------------------- 105.6/351.2 MB 8.3 MB/s eta 0:00:30
   ------------ --------------------------- 107.7/351.2 MB 8.1 MB/s eta 0:00:30
   ------------ --------------------------- 110.4/351.2 MB 8.1 MB/s eta 0:00:30
   ------------ --------------------------- 111.9/351.2 MB 8.0 MB/s eta 0:00:30
   ------------- -------------------------- 114.8/351.2 MB 8.0 MB/s eta 0:00:30
   ------------- -------------------------- 122.7/351.2 MB 8.3 MB/s eta 0:00:28
   -------------- ------------------------- 125.0/351.2 MB 8.4 MB/s eta 0:00:28
   -------------- ------------------------- 129.0/351.2 MB 8.5 MB/s eta 0:00:27
   --------------- ------------------------ 132.4/351.2 MB 8.6 MB/s eta 0:00:26
   --------------- ------------------------ 135.5/351.2 MB 8.6 MB/s eta 0:00:25
   --------------- ------------------------ 136.6/351.2 MB 8.6 MB/s eta 0:00:26
   --------------- ------------------------ 138.1/351.2 MB 8.5 MB/s eta 0:00:25
   ---------------- ----------------------- 140.5/351.2 MB 8.6 MB/s eta 0:00:25
   ---------------- ----------------------- 143.7/351.2 MB 8.6 MB/s eta 0:00:25
   ---------------- ----------------------- 147.1/351.2 MB 8.7 MB/s eta 0:00:24
   ----------------- ---------------------- 151.3/351.2 MB 8.9 MB/s eta 0:00:23
   ----------------- ---------------------- 155.5/351.2 MB 9.0 MB/s eta 0:00:22
   ------------------ --------------------- 159.1/351.2 MB 9.1 MB/s eta 0:00:22
   ------------------ --------------------- 161.5/351.2 MB 9.1 MB/s eta 0:00:21
   ------------------ --------------------- 165.7/351.2 MB 9.2 MB/s eta 0:00:21
   ------------------- -------------------- 169.1/351.2 MB 9.3 MB/s eta 0:00:20
   ------------------- -------------------- 173.0/351.2 MB 9.4 MB/s eta 0:00:19
   -------------------- ------------------- 176.9/351.2 MB 9.5 MB/s eta 0:00:19
   -------------------- ------------------- 180.1/351.2 MB 9.6 MB/s eta 0:00:18
   -------------------- ------------------- 184.3/351.2 MB 9.7 MB/s eta 0:00:18
   --------------------- ------------------ 189.0/351.2 MB 9.8 MB/s eta 0:00:17
   --------------------- ------------------ 191.6/351.2 MB 9.8 MB/s eta 0:00:17
   ---------------------- ----------------- 193.5/351.2 MB 9.8 MB/s eta 0:00:17
   ---------------------- ----------------- 197.4/351.2 MB 9.9 MB/s eta 0:00:16
   ---------------------- ---------------- 201.3/351.2 MB 10.0 MB/s eta 0:00:15
   ---------------------- ---------------- 205.0/351.2 MB 10.1 MB/s eta 0:00:15
   ----------------------- --------------- 208.7/351.2 MB 10.2 MB/s eta 0:00:15
   ----------------------- --------------- 212.9/351.2 MB 10.2 MB/s eta 0:00:14
   ------------------------ -------------- 217.3/351.2 MB 10.3 MB/s eta 0:00:13
   ------------------------ -------------- 222.6/351.2 MB 10.5 MB/s eta 0:00:13
   ------------------------- ------------- 227.3/351.2 MB 10.6 MB/s eta 0:00:12
   ------------------------- ------------- 231.2/351.2 MB 10.7 MB/s eta 0:00:12
   -------------------------- ------------ 235.7/351.2 MB 10.8 MB/s eta 0:00:11
   -------------------------- ------------ 239.6/351.2 MB 10.9 MB/s eta 0:00:11
   --------------------------- ----------- 244.3/351.2 MB 11.0 MB/s eta 0:00:10
   --------------------------- ----------- 249.3/351.2 MB 11.1 MB/s eta 0:00:10
   ---------------------------- ---------- 253.5/351.2 MB 11.1 MB/s eta 0:00:09
   ---------------------------- ---------- 256.9/351.2 MB 11.2 MB/s eta 0:00:09
   ---------------------------- ---------- 260.6/351.2 MB 11.1 MB/s eta 0:00:09
   ----------------------------- --------- 262.1/351.2 MB 11.1 MB/s eta 0:00:09
   ----------------------------- --------- 263.7/351.2 MB 11.0 MB/s eta 0:00:08
   ----------------------------- --------- 264.5/351.2 MB 10.9 MB/s eta 0:00:08
   ----------------------------- --------- 266.3/351.2 MB 11.0 MB/s eta 0:00:08
   ----------------------------- --------- 267.4/351.2 MB 10.9 MB/s eta 0:00:08
   ----------------------------- --------- 269.7/351.2 MB 10.8 MB/s eta 0:00:08
   ------------------------------ -------- 278.1/351.2 MB 11.2 MB/s eta 0:00:07
   ------------------------------- ------- 282.1/351.2 MB 11.3 MB/s eta 0:00:07
   ------------------------------- ------- 284.4/351.2 MB 11.2 MB/s eta 0:00:06
   ------------------------------- ------- 284.4/351.2 MB 11.2 MB/s eta 0:00:06
   ------------------------------- ------- 285.2/351.2 MB 11.0 MB/s eta 0:00:06
   ------------------------------- ------- 286.0/351.2 MB 10.9 MB/s eta 0:00:06
   ------------------------------- ------- 286.5/351.2 MB 10.9 MB/s eta 0:00:06
   ------------------------------- ------- 288.1/351.2 MB 10.8 MB/s eta 0:00:06
   -------------------------------- ------ 288.6/351.2 MB 10.7 MB/s eta 0:00:06
   -------------------------------- ------ 289.7/351.2 MB 10.6 MB/s eta 0:00:06
   -------------------------------- ------ 289.7/351.2 MB 10.6 MB/s eta 0:00:06
   -------------------------------- ------ 291.8/351.2 MB 10.6 MB/s eta 0:00:06
   -------------------------------- ------ 293.6/351.2 MB 10.7 MB/s eta 0:00:06
   -------------------------------- ------ 294.4/351.2 MB 10.6 MB/s eta 0:00:06
   -------------------------------- ------ 295.4/351.2 MB 10.4 MB/s eta 0:00:06
   --------------------------------- ----- 297.5/351.2 MB 10.6 MB/s eta 0:00:06
   --------------------------------- ----- 299.6/351.2 MB 10.5 MB/s eta 0:00:05
   --------------------------------- ----- 302.5/351.2 MB 10.6 MB/s eta 0:00:05
   --------------------------------- ----- 304.1/351.2 MB 10.5 MB/s eta 0:00:05
   ---------------------------------- ---- 314.0/351.2 MB 10.6 MB/s eta 0:00:04
   ----------------------------------- --- 316.9/351.2 MB 10.6 MB/s eta 0:00:04
   ----------------------------------- --- 316.9/351.2 MB 10.6 MB/s eta 0:00:04
   ----------------------------------- --- 316.9/351.2 MB 10.6 MB/s eta 0:00:04
   ----------------------------------- --- 316.9/351.2 MB 10.6 MB/s eta 0:00:04
   ----------------------------------- --- 316.9/351.2 MB 10.6 MB/s eta 0:00:04
   ----------------------------------- --- 317.7/351.2 MB 10.0 MB/s eta 0:00:04
   ------------------------------------ -- 325.6/351.2 MB 10.0 MB/s eta 0:00:03
   ------------------------------------ -- 329.3/351.2 MB 10.0 MB/s eta 0:00:03
   ------------------------------------ -- 332.4/351.2 MB 10.0 MB/s eta 0:00:02
   ------------------------------------- - 335.5/351.2 MB 10.0 MB/s eta 0:00:02
   ------------------------------------- - 339.2/351.2 MB 10.0 MB/s eta 0:00:02
   ---------------------------------------  342.6/351.2 MB 9.9 MB/s eta 0:00:01
   --------------------------------------  346.6/351.2 MB 10.2 MB/s eta 0:00:01
   --------------------------------------  350.5/351.2 MB 10.3 MB/s eta 0:00:01
   --------------------------------------  351.0/351.2 MB 10.3 MB/s eta 0:00:01
   --------------------------------------  351.0/351.2 MB 10.3 MB/s eta 0:00:01
   --------------------------------------  351.0/351.2 MB 10.3 MB/s eta 0:00:01
   --------------------------------------  351.0/351.2 MB 10.3 MB/s eta 0:00:01
   --------------------------------------  351.0/351.2 MB 10.3 MB/s eta 0:00:01
   --------------------------------------  351.0/351.2 MB 10.3 MB/s eta 0:00:01
   ---------------------------------------- 351.2/351.2 MB 9.8 MB/s  0:00:36
Downloading grpcio-1.80.0-cp313-cp313-win_amd64.whl (4.9 MB)
   ---------------------------------------- 0.0/4.9 MB ? eta -:--:--
   -------------------------------- ------- 3.9/4.9 MB 18.6 MB/s eta 0:00:01
   ---------------------------------------- 4.9/4.9 MB 16.4 MB/s  0:00:00
Downloading h5py-3.14.0-cp313-cp313-win_amd64.whl (2.9 MB)
   ---------------------------------------- 0.0/2.9 MB ? eta -:--:--
   ---------------------------------------- 2.9/2.9 MB 18.7 MB/s  0:00:00
Downloading ml_dtypes-0.5.4-cp313-cp313-win_amd64.whl (212 kB)
Downloading protobuf-7.34.1-cp310-abi3-win_amd64.whl (437 kB)
Downloading absl_py-2.4.0-py3-none-any.whl (135 kB)
Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Downloading flatbuffers-25.12.19-py2.py3-none-any.whl (26 kB)
Downloading gast-0.7.0-py3-none-any.whl (22 kB)
Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
Downloading keras-3.14.0-py3-none-any.whl (1.6 MB)
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ---------------------------------------- 1.6/1.6 MB 15.7 MB/s  0:00:00
Downloading libclang-18.1.1-py2.py3-none-win_amd64.whl (26.4 MB)
   ---------------------------------------- 0.0/26.4 MB ? eta -:--:--
   ------ --------------------------------- 4.2/26.4 MB 22.0 MB/s eta 0:00:02
   ------------ --------------------------- 8.4/26.4 MB 19.9 MB/s eta 0:00:01
   ------------------- -------------------- 12.8/26.4 MB 20.0 MB/s eta 0:00:01
   ------------------------- -------------- 16.5/26.4 MB 19.5 MB/s eta 0:00:01
   ------------------------------ --------- 20.4/26.4 MB 19.1 MB/s eta 0:00:01
   ------------------------------------ --- 24.1/26.4 MB 18.6 MB/s eta 0:00:01
   ---------------------------------------  26.2/26.4 MB 18.2 MB/s eta 0:00:01
   ---------------------------------------- 26.4/26.4 MB 17.1 MB/s  0:00:01
Downloading opt_einsum-3.4.0-py3-none-any.whl (71 kB)
Downloading termcolor-3.3.0-py3-none-any.whl (7.7 kB)
Downloading namex-0.1.0-py3-none-any.whl (5.9 kB)
Downloading optree-0.19.0-cp313-cp313-win_amd64.whl (337 kB)
Installing collected packages: namex, libclang, flatbuffers, termcolor, protobuf, optree, opt_einsum, ml_dtypes, h5py, grpcio, google_pasta, gast, astunparse, absl-py, keras, tensorflow

   -- -------------------------------------  1/16 [libclang]
   -- -------------------------------------  1/16 [libclang]
   -- -------------------------------------  1/16 [libclang]
   -- -------------------------------------  1/16 [libclang]
   -- -------------------------------------  1/16 [libclang]
   -- -------------------------------------  1/16 [libclang]
   -- -------------------------------------  1/16 [libclang]
   ------- --------------------------------  3/16 [termcolor]
  Attempting uninstall: protobuf
   ------- --------------------------------  3/16 [termcolor]
    Found existing installation: protobuf 5.29.3
   ------- --------------------------------  3/16 [termcolor]
    Uninstalling protobuf-5.29.3:
   ------- --------------------------------  3/16 [termcolor]
      Successfully uninstalled protobuf-5.29.3
   ------- --------------------------------  3/16 [termcolor]
   ---------- -----------------------------  4/16 [protobuf]
   ---------- -----------------------------  4/16 [protobuf]
   ---------- -----------------------------  4/16 [protobuf]
   ---------- -----------------------------  4/16 [protobuf]
   ---------- -----------------------------  4/16 [protobuf]
   ------------ ---------------------------  5/16 [optree]
   --------------- ------------------------  6/16 [opt_einsum]
   --------------- ------------------------  6/16 [opt_einsum]
  Attempting uninstall: h5py
   --------------- ------------------------  6/16 [opt_einsum]
    Found existing installation: h5py 3.15.1
   --------------- ------------------------  6/16 [opt_einsum]
   -------------------- -------------------  8/16 [h5py]
    Uninstalling h5py-3.15.1:
   -------------------- -------------------  8/16 [h5py]
      Successfully uninstalled h5py-3.15.1
   -------------------- -------------------  8/16 [h5py]
   -------------------- -------------------  8/16 [h5py]
   -------------------- -------------------  8/16 [h5py]
   -------------------- -------------------  8/16 [h5py]
   -------------------- -------------------  8/16 [h5py]
   -------------------- -------------------  8/16 [h5py]
   ---------------------- -----------------  9/16 [grpcio]
   ---------------------- -----------------  9/16 [grpcio]
   ---------------------- -----------------  9/16 [grpcio]
   ---------------------- -----------------  9/16 [grpcio]
   ------------------------- -------------- 10/16 [google_pasta]
   ------------------------- -------------- 10/16 [google_pasta]
   ------------------------------ --------- 12/16 [astunparse]
   -------------------------------- ------- 13/16 [absl-py]
   -------------------------------- ------- 13/16 [absl-py]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.51.0 requires protobuf<7,>=3.20, but you have protobuf 7.34.1 which is incompatible.

In [3]:
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [4]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [5]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [6]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [16]:
X = df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y = df["needs_water"]

In [ ]:
X_min = X.min()
X_max = X.max()
X_scaled = (X - X_min) / (X_max - X_min + 1e-8)

In [11]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.25, random_state=42)

In [18]:
model = keras.Sequential([
    layers.Input(shape = (X_train.shape[1], )),
    layers.Dense(8, activation="relu"),
    layers.Dense(1, activation="sigmoid")
])

In [ ]:
model.compile(optimizer="sgd", loss="binary_crossentropy", metrics=["accuracy"])